#include <ntddk.h>
#include <wdf.h>

#include "Device.h"
#include "Trace.h"
#include "Driver.tmh"  // Auto-generated by WPP preprocessor

extern "C" DRIVER_INITIALIZE DriverEntry;
EVT_WDF_DRIVER_DEVICE_ADD TouchEvtDeviceAdd;
EVT_WDF_DRIVER_UNLOAD TouchEvtDriverUnload;

_Use_decl_annotations_
NTSTATUS DriverEntry(PDRIVER_OBJECT driverObject, PUNICODE_STRING registryPath)
{
    // Initialize WPP Tracing
    WPP_INIT_TRACING(driverObject, registryPath);

    TRACE_FUNCTION_ENTRY(TRACE_DRIVER);
    TRACE_INFO(TRACE_DRIVER, "RoboPeak USB Touch HID Driver v1.0.0");

    WDF_DRIVER_CONFIG config;
    WDF_DRIVER_CONFIG_INIT(&config, TouchEvtDeviceAdd);
    config.EvtDriverUnload = TouchEvtDriverUnload;

    TRACE_INFO(TRACE_DRIVER, "Creating WDF driver");

    NTSTATUS status = WdfDriverCreate(driverObject, registryPath, WDF_NO_OBJECT_ATTRIBUTES, &config, WDF_NO_HANDLE);

    if (!NT_SUCCESS(status))
    {
        TRACE_ERROR(TRACE_DRIVER, "WdfDriverCreate failed: %!STATUS!", status);
        WPP_CLEANUP(driverObject);
    }
    else
    {
        TRACE_INFO(TRACE_DRIVER, "WDF driver created successfully");
    }

    TRACE_FUNCTION_EXIT_NTSTATUS(TRACE_DRIVER, status);
    return status;
}

_Use_decl_annotations_
NTSTATUS TouchEvtDeviceAdd(WDFDRIVER /*driver*/, PWDFDEVICE_INIT deviceInit)
{
    TRACE_FUNCTION_ENTRY(TRACE_DRIVER);
    TRACE_INFO(TRACE_DRIVER, "Adding HID touch device");

    NTSTATUS status = TouchDeviceCreate(deviceInit);

    if (NT_SUCCESS(status))
    {
        TRACE_INFO(TRACE_DRIVER, "HID touch device added successfully");
    }
    else
    {
        TRACE_ERROR(TRACE_DRIVER, "TouchDeviceCreate failed: %!STATUS!", status);
    }

    TRACE_FUNCTION_EXIT_NTSTATUS(TRACE_DRIVER, status);
    return status;
}

_Use_decl_annotations_
VOID TouchEvtDriverUnload(WDFDRIVER driver)
{
    TRACE_FUNCTION_ENTRY(TRACE_DRIVER);
    TRACE_INFO(TRACE_DRIVER, "RoboPeak USB Touch HID Driver unloading");

    // Clean up WPP Tracing
    WPP_CLEANUP(WdfDriverWdmGetDriverObject(driver));

    TRACE_FUNCTION_EXIT(TRACE_DRIVER);
}
