#include <ntddk.h>
#include <wdf.h>

#include "Device.h"
#include "Trace.h"
#include "Driver.tmh"  // Auto-generated by WPP preprocessor

extern "C" DRIVER_INITIALIZE DriverEntry;
EVT_WDF_DRIVER_DEVICE_ADD UsbEvtDeviceAdd;
EVT_WDF_DRIVER_UNLOAD UsbEvtDriverUnload;

_Use_decl_annotations_
NTSTATUS DriverEntry(PDRIVER_OBJECT driverObject, PUNICODE_STRING registryPath)
{
    // Initialize WPP Tracing
    WPP_INIT_TRACING(driverObject, registryPath);

    TRACE_FUNCTION_ENTRY(TRACE_DRIVER);
    TRACE_INFO(TRACE_DRIVER, "RoboPeak USB Transport Driver v1.0.0");

    WDF_DRIVER_CONFIG config;
    WDF_DRIVER_CONFIG_INIT(&config, UsbEvtDeviceAdd);
    config.EvtDriverUnload = UsbEvtDriverUnload;

    WDF_OBJECT_ATTRIBUTES attributes;
    WDF_OBJECT_ATTRIBUTES_INIT(&attributes);

    NTSTATUS status = WdfDriverCreate(driverObject, registryPath, &attributes, &config, WDF_NO_HANDLE);

    if (!NT_SUCCESS(status))
    {
        TRACE_ERROR(TRACE_DRIVER, "WdfDriverCreate failed: %!STATUS!", status);
        WPP_CLEANUP(driverObject);
        return status;
    }

    TRACE_FUNCTION_EXIT_NTSTATUS(TRACE_DRIVER, status);
    return status;
}

_Use_decl_annotations_
NTSTATUS UsbEvtDeviceAdd(WDFDRIVER driver, PWDFDEVICE_INIT deviceInit)
{
    UNREFERENCED_PARAMETER(driver);

    TRACE_FUNCTION_ENTRY(TRACE_DRIVER);

    NTSTATUS status = UsbDeviceCreate(deviceInit);

    if (!NT_SUCCESS(status))
    {
        TRACE_ERROR(TRACE_DRIVER, "UsbDeviceCreate failed: %!STATUS!", status);
    }
    else
    {
        TRACE_INFO(TRACE_DRIVER, "USB device added successfully");
    }

    TRACE_FUNCTION_EXIT_NTSTATUS(TRACE_DRIVER, status);
    return status;
}

_Use_decl_annotations_
VOID UsbEvtDriverUnload(WDFDRIVER driver)
{
    TRACE_FUNCTION_ENTRY(TRACE_DRIVER);
    TRACE_INFO(TRACE_DRIVER, "RoboPeak USB Transport Driver unloading");

    // Cleanup WPP Tracing
    WPP_CLEANUP(WdfDriverWdmGetDriverObject(driver));

    TRACE_FUNCTION_EXIT(TRACE_DRIVER);
}
