#include <ntddk.h>
#include <wdf.h>
#include <IddCx.h>

#include "DisplayDevice.h"
#include "Pipeline.h"
#include "Trace.h"
#include "Driver.tmh"  // Auto-generated by WPP preprocessor

extern "C" DRIVER_INITIALIZE DriverEntry;
EVT_WDF_DRIVER_DEVICE_ADD DisplayEvtDeviceAdd;
EVT_WDF_DRIVER_UNLOAD DisplayEvtDriverUnload;

_Use_decl_annotations_
NTSTATUS DriverEntry(PDRIVER_OBJECT driverObject, PUNICODE_STRING registryPath)
{
    // Initialize WPP Tracing
    WPP_INIT_TRACING(driverObject, registryPath);

    TRACE_FUNCTION_ENTRY(TRACE_DRIVER);
    TRACE_INFO(TRACE_DRIVER, "RoboPeak USB Display IDD Driver v1.0.0");

    WDF_DRIVER_CONFIG config;
    WDF_DRIVER_CONFIG_INIT(&config, DisplayEvtDeviceAdd);
    config.DriverInitFlags |= WdfDriverInitNonPnpDriver;
    config.DriverPoolTag = 'RUSB';

    NTSTATUS status = WdfDriverCreate(driverObject, registryPath, WDF_NO_OBJECT_ATTRIBUTES, &config, WDF_NO_HANDLE);

    if (!NT_SUCCESS(status))
    {
        TRACE_ERROR(TRACE_DRIVER, "WdfDriverCreate failed: %!STATUS!", status);
        WPP_CLEANUP(driverObject);
        return status;
    }

    TRACE_FUNCTION_EXIT_NTSTATUS(TRACE_DRIVER, status);
    return status;
}

_Use_decl_annotations_
NTSTATUS DisplayEvtDeviceAdd(WDFDRIVER driver, PWDFDEVICE_INIT deviceInit)
{
    UNREFERENCED_PARAMETER(driver);

    TRACE_FUNCTION_ENTRY(TRACE_DRIVER);

    WdfDeviceInitSetDeviceType(deviceInit, FILE_DEVICE_UNKNOWN);
    WdfDeviceInitSetExclusive(deviceInit, FALSE);

    WDF_PNPPOWER_EVENT_CALLBACKS pnpCallbacks;
    WDF_PNPPOWER_EVENT_CALLBACKS_INIT(&pnpCallbacks);
    pnpCallbacks.EvtDevicePrepareHardware = DisplayEvtPrepareHardware;
    pnpCallbacks.EvtDeviceReleaseHardware = DisplayEvtReleaseHardware;
    pnpCallbacks.EvtDeviceSurpriseRemoval = DisplayEvtSurpriseRemoval;
    pnpCallbacks.EvtDeviceD0Entry = DisplayEvtD0Entry;
    pnpCallbacks.EvtDeviceD0Exit = DisplayEvtD0Exit;
    WdfDeviceInitSetPnpPowerEventCallbacks(deviceInit, &pnpCallbacks);

    WDF_OBJECT_ATTRIBUTES attributes;
    WDF_OBJECT_ATTRIBUTES_INIT_CONTEXT_TYPE(&attributes, DisplayDeviceContext);

    WDFDEVICE device;
    NTSTATUS status = WdfDeviceCreate(&deviceInit, &attributes, &device);
    if (!NT_SUCCESS(status))
    {
        TRACE_ERROR(TRACE_DRIVER, "WdfDeviceCreate failed: %!STATUS!", status);
        return status;
    }

    TRACE_INFO(TRACE_DEVICE, "Display device created successfully");

    auto* context = GetDisplayContext(device);
    context->WdfDevice = device;

    status = PipelineInitialize(device);
    if (!NT_SUCCESS(status))
    {
        TRACE_ERROR(TRACE_DRIVER, "PipelineInitialize failed: %!STATUS!", status);
    }
    else
    {
        TRACE_INFO(TRACE_DRIVER, "Display device added successfully");
    }

    TRACE_FUNCTION_EXIT_NTSTATUS(TRACE_DRIVER, status);
    return status;
}

_Use_decl_annotations_
VOID DisplayEvtDriverUnload(WDFDRIVER driver)
{
    TRACE_FUNCTION_ENTRY(TRACE_DRIVER);
    TRACE_INFO(TRACE_DRIVER, "RoboPeak USB Display IDD Driver unloading");

    PipelineTeardown();

    // Cleanup WPP Tracing
    WPP_CLEANUP(WdfDriverWdmGetDriverObject(driver));

    TRACE_FUNCTION_EXIT(TRACE_DRIVER);
}
