#pragma once

#include <initguid.h>
#include <winioctl.h>

// {A1D66B33-4584-4D4E-868C-9B7E7D671D4D}
DEFINE_GUID(GUID_DEVINTERFACE_RPUSB_TRANSPORT,
            0xa1d66b33, 0x4584, 0x4d4e, 0x86, 0x8c, 0x9b, 0x7e, 0x7d, 0x67, 0x1d, 0x4d);

#define FILE_DEVICE_RPUSB_TRANSPORT 0x8331

#define IOCTL_RPUSB_PING               CTL_CODE(FILE_DEVICE_RPUSB_TRANSPORT, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_RPUSB_GET_VERSION        CTL_CODE(FILE_DEVICE_RPUSB_TRANSPORT, 0x801, METHOD_BUFFERED, FILE_READ_ACCESS)
#define IOCTL_RPUSB_PUSH_FRAME         CTL_CODE(FILE_DEVICE_RPUSB_TRANSPORT, 0x802, METHOD_OUT_DIRECT, FILE_WRITE_ACCESS)
#define IOCTL_RPUSB_SET_MODE           CTL_CODE(FILE_DEVICE_RPUSB_TRANSPORT, 0x803, METHOD_BUFFERED, FILE_WRITE_ACCESS)
#define IOCTL_RPUSB_GET_STATISTICS     CTL_CODE(FILE_DEVICE_RPUSB_TRANSPORT, 0x804, METHOD_BUFFERED, FILE_READ_ACCESS)
#define IOCTL_RPUSB_REGISTER_LISTENER  CTL_CODE(FILE_DEVICE_RPUSB_TRANSPORT, 0x805, METHOD_BUFFERED, FILE_ANY_ACCESS)

struct RPUSB_DRIVER_VERSION
{
    UINT16 Major;
    UINT16 Minor;
    UINT16 Patch;
};

struct RPUSB_FRAME_HEADER
{
    UINT32 Width;
    UINT32 Height;
    UINT32 PixelFormat; // DXGI_FORMAT
    UINT32 PayloadBytes;
};

struct RPUSB_STATISTICS
{
    UINT64 FramesSubmitted;
    UINT64 FramesAcked;
    UINT64 BytesTransferred;
    UINT64 LastError;
};
